openapi: 3.2.0
info:
  title: LLM-ready ID API
  version: 0.1.0
  description: S&P Global Market Intelligence kFinance dataset via LLM-Ready API
servers:
- url: https://kfinance.kensho.com
tags:
- name: Id
paths:
  /api/v1/id/{cusip}:
    get:
      operationId: CUSIP to Identification Triple
      description: Get the most likely trading_item_id, security_id, and company_id with a given CUSIP.
      parameters:
      - in: path
        name: cusip
        schema:
          type: string
          pattern: ^[a-zA-Z0-9*@#]{8}[0-9]$
        required: true
      security:
      - cookieAuth: []
      - Kensho_JWT_Auth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentificationTripleWithCompanyInfoResponse'
              examples:
                CUSIPToIDTripleExample:
                  value:
                    trading_item_id: 2590360
                    security_id: 2590359
                    company_id: 24937
                    company_name: Apple, Inc.
                    ticker: NasdaqGS:AAPL
                  summary: US0378331005
          description: Indicates a successful request.
        '400':
          description: Indicates that the query is invalid.
        '403':
          description: Indicates that the authorization information is missing or invalid.
      tags:
      - Id
      summary: CUSIP to identification triple
      x-summary-source: derived
  /api/v1/id/{isin}:
    get:
      operationId: ISIN to Identification Triple
      description: Get the most likely trading_item_id, security_id, and company_id with a given ISIN.
      parameters:
      - in: path
        name: isin
        schema:
          type: string
          pattern: ^[a-zA-Z]{2}[a-zA-Z0-9]{9}[0-9]$
        required: true
      security:
      - cookieAuth: []
      - Kensho_JWT_Auth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentificationTripleWithCompanyInfoResponse'
              examples:
                ISINToIDTripleExample:
                  value:
                    trading_item_id: 2590360
                    security_id: 2590359
                    company_id: 24937
                    company_name: Apple, Inc.
                    ticker: NasdaqGS:AAPL
                  summary: US0378331005
          description: Indicates a successful request.
        '400':
          description: Indicates that the query is invalid.
        '403':
          description: Indicates that the authorization information is missing or invalid.
      tags:
      - Id
      summary: ISIN to identification triple
      x-summary-source: derived
  /api/v1/id/{ticker}:
    get:
      operationId: Ticker to Identification Triple
      description: Get the most likely trading_item_id, security_id, and company_id with a given ticker symbol.
      parameters:
      - in: path
        name: ticker
        schema:
          type: string
        required: true
      security:
      - cookieAuth: []
      - Kensho_JWT_Auth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentificationTripleWithCompanyInfoResponse'
              examples:
                TickerToIDTripleExample:
                  value:
                    trading_item_id: 2590360
                    security_id: 2590359
                    company_id: 24937
                    company_name: Apple, Inc.
                    ticker: NasdaqGS:AAPL
                  summary: AAPL
          description: Indicates a successful request.
        '400':
          description: Indicates that the query is invalid.
        '403':
          description: Indicates that the authorization information is missing or invalid.
      tags:
      - Id
      summary: Ticker to identification triple
      x-summary-source: derived
  /api/v1/id/{ticker}/exchange_code/{exchange_code}:
    get:
      operationId: Ticker to Identification Triple_2
      description: Get the most likely trading_item_id, security_id, and company_id with a given ticker symbol.
      parameters:
      - in: path
        name: exchange_code
        schema:
          type: string
        required: true
      - in: path
        name: ticker
        schema:
          type: string
        required: true
      security:
      - cookieAuth: []
      - Kensho_JWT_Auth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentificationTripleWithCompanyInfoResponse'
              examples:
                TickerToIDTripleExample:
                  value:
                    trading_item_id: 2590360
                    security_id: 2590359
                    company_id: 24937
                    company_name: Apple, Inc.
                    ticker: NasdaqGS:AAPL
                  summary: AAPL
          description: Indicates a successful request.
        '400':
          description: Indicates that the query is invalid.
        '403':
          description: Indicates that the authorization information is missing or invalid.
      tags:
      - Id
      summary: Ticker to identification triple 2
      x-summary-source: derived
components:
  schemas:
    IdentificationTripleWithCompanyInfoResponse:
      type: object
      description: Response fields for a request returning an identification triple with company info
      properties:
        trading_item_id:
          type:
          - integer
          - 'null'
        security_id:
          type:
          - integer
          - 'null'
        company_id:
          type: integer
        company_name:
          type: string
        ticker:
          type:
          - string
          - 'null'
        country:
          type:
          - string
          - 'null'
      required:
      - company_id
      - company_name
      - country
      - security_id
      - ticker
      - trading_item_id
  securitySchemes:
    Kensho_JWT_Auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
